In [184]:
import numpy as np
import pandas as pd

from talib import RSI, BBANDS, MACD, ATR, MOM, ROC

# Read in QQQ data

In [185]:
qqq = pd.read_csv('data/QQQ.csv', index_col=0)

qqq.drop('Close', axis=1, inplace=True)
qqq.columns = ['open', 'high', 'low', 'close', 'volume']
qqq.index.rename('date', inplace=True)

# Calculate technical indicators for QQQ

In [186]:
# Calculate RSI
qqq['rsi'] = RSI(qqq['close'], timeperiod=14)

# Calculate Bolinger Bands, take only high and low
high, mid, low = BBANDS(qqq['close'], timeperiod=20)
bbdf = pd.DataFrame({'bb_high': high, 'bb_low': low}, index=qqq.index)
qqq = qqq.join(bbdf)

# Take the log of the percentage difference between close price and bbands
qqq['bb_high'] = qqq.bb_high.sub(qqq.close).div(qqq.bb_high).apply(np.log1p)
qqq['bb_low'] = qqq.close.sub(qqq.bb_low).div(qqq.close).apply(np.log1p)

# Calculate the average true range: NOTE: he standardizes the result to make it more comparable across stocks
# but we're only focused one one stock so I didn't
qqq['atr'] = ATR(qqq.high, qqq.low, qqq.close, timeperiod=14)

# Calculate MACD: I think he standardizes here too, I won't again.
qqq['macd'] = MACD(qqq.close,fastperiod=12, slowperiod=26, signalperiod=9)[0]

# Calculate momentum
qqq['mom'] = MOM(qqq.close, timeperiod=10)

# Calculate rate-of-change
qqq['roc'] = ROC(qqq.close, timeperiod=10)

# Read in and prepare DXY

In [187]:
dxy = pd.read_csv('data/dxy.csv', index_col=0)
dxy.index = pd.to_datetime(dxy.index).rename('date')
dxy.sort_index(inplace=True)
dxy.columns = ['close', 'open', 'high', 'low', 'volume', 'dxy_daily']
dxy.drop('volume', axis=1, inplace=True)
dxy['dxy_daily'] = dxy.dxy_daily.str.replace('%', '').astype(float).div(100)

# Needed two csvs to cover the full date range due to the websites requirement.
dxy2 = pd.read_csv('data/dxy2.csv', index_col=0)
dxy2.index = pd.to_datetime(dxy2.index).rename('date')
dxy2.sort_index(inplace=True)
dxy2.columns = ['close', 'open', 'high', 'low', 'volume', 'dxy_daily']
dxy2.drop('volume', axis=1, inplace=True)
dxy2['dxy_daily'] = dxy2.dxy_daily.str.replace('%', '').astype(float).div(100)

# Combine and drop duplicate dates
dxy = pd.concat([dxy, dxy2])
dxy = dxy[~dxy.index.duplicated(keep='first')].sort_index()

# Create some rolling averages. NOTE: THESE ARE SIMPLE AVERAGES, not the geometric means used when calculating QQQ returns.
# We can change this if we want to but decided to keep it simple for now.
for w in [5,10,14,21,30]:
    dxy[f'dxy_rolling_{w}_day'] = dxy['dxy_daily'].rolling(window=w).mean()

dxy.drop(['close', 'open', 'high', 'low'], axis=1, inplace=True)

# Read in EEM

Not too sure how to process this, but will read in for now and compute some rolling windows

In [188]:
eem = pd.read_csv('data/EEM.csv', index_col=0)

eem.drop('Close', axis=1, inplace=True)
eem.columns = ['open', 'high', 'low', 'close', 'volume']
eem.index.rename('date', inplace=True)

# EMMA: Here would be where we did any sort of computations you need
eem['eem_daily'] = eem['close'].pct_change()
for w in [5,10,14,21,30]:
    eem[f'eem_rolling_{w}_day'] = eem['eem_daily'].rolling(window=w).mean()

eem.drop(['close', 'open', 'high', 'low', 'volume'], axis=1, inplace=True)

# Read in top QQQ stocks

In [189]:
# Note: Amazon seems to still be a part of the nasdaq, so included it here. Can drop that or TSLA if we wanna keep to 5

aapl = pd.read_csv('data/AAPL.csv', index_col=0)
amzn = pd.read_csv('data/AMZN.csv', index_col=0)
fb = pd.read_csv('data/FB.csv', index_col=0)
msft = pd.read_csv('data/MSFT.csv', index_col=0)
goog = pd.read_csv('data/GOOG.csv', index_col=0)
tsla = pd.read_csv('data/TSLA.csv', index_col=0)

stocks = [aapl, amzn, fb, msft, goog, tsla]
tickers = ['aapl', 'amzn', 'fb', 'msft', 'goog', 'tsla']

for i in range(len(stocks)):
    stock = stocks[i]
    ticker = tickers[i]
    stock.drop('Close', axis=1, inplace=True)
    stock.columns = ['open', 'high', 'low', 'close', 'volume']
    stock.index.rename('date', inplace=True)
    
    # EMMA: Here would be where we did any sort of computations you need
    stock[f'{ticker}_daily'] = stock['close'].pct_change()
    
    for w in [5,10,14,21,30]:
        stock[f'{ticker}_rolling_{w}_day'] = stock[f'{ticker}_daily'].rolling(window=w).mean()

    stock.drop(['close', 'open', 'high', 'low', 'volume'], axis=1, inplace=True)

# Additional tickers

GLD and ^TNX. Following the same drill here, but just change the computation part for different metrics

In [192]:

gld = pd.read_csv('data/GLD.csv', index_col=0)
tnx = pd.read_csv('data/^TNX.csv', index_col=0)
vix = pd.read_csv('data/^VIX.csv', index_col=0)
jnk = pd.read_csv('data/JNK.csv', index_col=0)

others = [gld, tnx, vix, jnk]
tickers = ['gld', 'tnx', 'vix', 'jnk']

for i in range(len(others)):
    stock = others[i]
    ticker = tickers[i]
    stock.drop('Close', axis=1, inplace=True)
    stock.columns = ['open', 'high', 'low', 'close', 'volume']
    stock.index.rename('date', inplace=True)
    
    # EMMA: Here would be where we did any sort of computations you need
    stock[f'{ticker}_daily'] = stock['close'].pct_change()
    
    for w in [5,10,14,21,30]:
        stock[f'{ticker}_rolling_{w}_day'] = stock[f'{ticker}_daily'].rolling(window=w).mean()

    stock.drop(['close', 'open', 'high', 'low', 'volume'], axis=1, inplace=True)

# Putting it all together
Birth of the big-ass dataframe

In [193]:
for datasource in ([dxy, eem] + stocks + others):
    qqq = qqq.join(datasource)

# Let's add some QQQ returns

I'm gonna use the lags he used for this section, feel free to change them. Also gonna windsorize because that makes sense too

In [194]:
lags = [1, 5, 10, 21, 42, 63]
q = 0.0001

# These returns ARE the geometric means btw.
for lag in lags:
    qqq[f'return_{lag}d'] = (qqq.close
                                .pct_change(lag)
                                .pipe(lambda x: x.clip(lower=x.quantile(q),
                                                       upper=x.quantile(1 - q)))
                                .add(1)
                                .pow(1 / lag)
                                .sub(1)
                                )

# Shifting the lags so we have multiple sets of returns for each date
for t in [1, 2, 3, 4, 5]:
    for lag in [1, 5, 10, 21]:
        qqq[f'return_{lag}d_lag{t}'] = (qqq[f'return_{lag}d'].shift(t * lag))

# Add some target variables

Simply shifting returns backwards so they can act as forward returns

In [195]:
for t in [1, 5, 10, 21]:
    qqq[f'target_{t}d'] = qqq[f'return_{t}d'].shift(-t)

# You wanted a big-ass dataframe?

...you got one

In [196]:
qqq

,open,high,low,close,volume,rsi,bb_high,bb_low,atr,macd,...,return_10d_lag4,return_21d_lag4,return_1d_lag5,return_5d_lag5,return_10d_lag5,return_21d_lag5,target_1d,target_5d,target_10d,target_21d
date,,,,,,,,,,,,,,,,,,,,,
1999-03-10,51.125000,51.156250,50.281250,44.523476,5232000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.004896,0.001951,-0.001169,0.004245
1999-03-11,51.437500,51.734375,50.312500,44.741455,9688600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.024361,0.004825,0.001932,0.003689
1999-03-12,51.125000,51.156250,49.656250,43.651520,8743600,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.028714,0.004577,0.003321,0.004217
1999-03-15,50.437500,51.562500,49.906250,44.904942,6369000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.008495,-0.003544,0.004052,0.001199
1999-03-16,51.718750,52.156250,51.156250,45.286419,4905800,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.007220,-0.012334,0.002499,0.001440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-06,293.709991,295.359985,289.829987,294.609985,40959800,61.558118,0.018474,0.086460,7.118914,1.465873,...,-0.007314,0.003403,-0.025363,0.002017,0.006615,0.003905,-0.020434,NaN,NaN,NaN
2020-11-09,297.649994,299.140015,288.119995,288.589996,86537100,55.533787,0.035281,0.068016,7.397564,1.776441,...,-0.006103,0.004839,0.002227,0.002127,0.007244,0.002488,-0.017915,NaN,NaN,NaN
2020-11-10,285.170013,286.660004,280.619995,283.420013,69024900,50.924553,0.047727,0.051233,7.438453,1.587099,...,-0.005499,0.004798,0.017298,-0.000573,0.006887,0.003468,0.022370,NaN,NaN,NaN
2020-11-11,286.029999,290.250000,283.380005,289.760010,36102900,55.772406,0.026095,0.070325,7.397849,1.926422,...,-0.008778,0.004317,0.044639,0.001493,0.007629,0.003506,-0.004694,NaN,NaN,NaN
2020-11-12,290.760010,292.070007,287.250000,288.399994,34414600,54.528049,0.029810,0.066046,7.213717,2.061828,...,-0.011269,0.003176,0.026071,-0.000596,0.009260,0.004011,NaN,NaN,NaN,NaN

In [197]:
qqq.to_csv('data/badf.csv')